'use client';

import React, { useEffect, useRef } from 'react';
import functionPlot from 'function-plot';

interface GraphRendererProps {
    fn: string;
    width?: number;
    height?: number;
}

export default function GraphRenderer({ fn, width = 400, height = 300 }: GraphRendererProps) {
    const rootEl = useRef<HTMLDivElement>(null);

    useEffect(() => {
        if (!rootEl.current) return;

        try {
            functionPlot({
                target: rootEl.current,
                width: width,
                height: height,
                yAxis: { domain: [-10, 10] },
                xAxis: { domain: [-10, 10] },
                grid: true,
                data: [
                    {
                        fn: fn,
                        color: '#3b82f6', // Blue-500
                        graphType: 'polyline'
                    }
                ],
                // Dark theme tweaks
                tip: {
                    xLine: true,
                    yLine: true,
                }
            });

            // Manual dark mode styling injection for the SVG generated by function-plot
            const svg = rootEl.current.querySelector('svg');
            if (svg) {
                svg.style.color = '#fff';
                const textElements = svg.querySelectorAll('text');
                textElements.forEach(el => (el as SVGElement).style.fill = '#888');
                const pathElements = svg.querySelectorAll('.domain');
                pathElements.forEach(el => (el as SVGElement).style.stroke = '#444');
            }

        } catch (e) {
            console.error("Graph rendering failed", e);
        }
    }, [fn, width, height]);

    return (
        <div className="flex justify-center bg-[#171717] rounded-xl overflow-hidden border border-white/10 p-2">
            <div ref={rootEl} />
        </div>
    );
}
